### ISSUE TITLE
normal integeration via add-on store

### ISSUE THREAD

**Issue by tcurdt** [SonnenladenGmbH/APsystems-EZ1-API-HomeAssistant#20]
Any progress on changing the fact that

> this is not a regular HA add-on that can be installed by just searching for it inside the add-on store.

?

**Comment by mawoka-myblock** [comment]
The problem is that the code would have to comply with HA's standards, which it doesn't and it would be a lot of work for, in my eyes, not much.

**Comment by tcurdt** [comment]
Could you elaborate on what standards it does not comply to?

**Comment by mawoka-myblock** [comment]
I can't remember exactly, but I think it was something regarding the data-fetching, as it's quite inefficient right now, as the data is getting fetched multiple times, but as I'm not a HA profi, it seemed quite complex to mitigate this issue.

**Comment by tcurdt** [comment]
Is there a link to where this was discussed?

**Comment by mawoka-myblock** [comment]
No, I discussed that with myself. ;) All in all, the problem is that the same data gets fetched multiple times. I also don't really feel comfortable in this regard, as I am not really experienced regarding HA development. 

As you can see in the https://github.com/SonnenladenGmbH/APsystems-EZ1-API-HomeAssistant/blob/main/custom_components/apsystemsapi_local/sensor.py file, the data gets pulled multiple times.

**Comment by tcurdt** [comment]
> No, I discussed that with myself. ;)

Well, it's hard to argue then ;-)

But what are the HA standards for add-ons?
Is this just you feeling it's not good enough? :)

As for the multiple calls - I guess it depends what options there are.
Does the EZ1 API allow to read data in bulk?
If so I don't think it's that complex to change.

**Comment by mawoka-myblock** [comment]
I fixed the last point. Will have to check if it's okay for @SonnenladenGmbH if this integration gets integrated into HA core. if so, I'll create a PR there and ping you in there, if that's fine for you.
